# Generated by Django 4.2.8 on 2023-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('table_shape', models.CharField(max_length=70)),
                ('coordinates_x', models.PositiveIntegerField()),
                ('coordinates_y', models.PositiveIntegerField()),
                ('table_width', models.PositiveIntegerField()),
                ('table_height', models.PositiveIntegerField()),
            ],
        ),
    ]
