# Generated by Django 4.2.8 on 2023-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tables_orders_alter_tables_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name': 'Столик', 'verbose_name_plural': 'Столики'},
        ),
        migrations.AlterField(
            model_name='tables',
            name='coordinates_x',
            field=models.PositiveIntegerField(verbose_name='Координата по Х'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='coordinates_y',
            field=models.PositiveIntegerField(verbose_name='Координата по Y'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='number_of_seats',
            field=models.PositiveIntegerField(verbose_name='Кількість місць'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_height',
            field=models.PositiveIntegerField(verbose_name='Довжина'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_number',
            field=models.PositiveIntegerField(verbose_name='Номер столика'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_shape',
            field=models.CharField(max_length=70, verbose_name='Форма столика'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_width',
            field=models.PositiveIntegerField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='tables_orders',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tables_orders',
            name='table_number',
            field=models.TextField(verbose_name='Номер(и) столика'),
        ),
    ]
