# Generated by Django 4.2.8 on 2023-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_tables_options_alter_tables_coordinates_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables_orders',
            name='table_number',
            field=models.PositiveIntegerField(verbose_name='Номер столика'),
        ),
    ]
