# Generated by Django 4.2.8 on 2023-12-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_tables_orders_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables_orders',
            name='user',
            field=models.CharField(default=1, max_length=250, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
